{
"cells":[
0:{
"cell_type":"code"
"execution_count":14
"id":"2f3e1f86-d17e-420e-bdea-07d2559e76ba"
"metadata":{}
"outputs":[]
"source":
[0 - 100]
[100 - 118]
}
1:{
"cell_type":"code"
"execution_count":NULL
"id":"93d912a6-257f-4b2f-b66e-32a6f8aecddd"
"metadata":{}
"outputs":[]
"source":[]
}
]
"metadata":{
"kernelspec":{
"display_name":"Python [conda env:base] *"
"language":"python"
"name":"conda-base-py"
}
"language_info":{
"codemirror_mode":{
"name":"ipython"
"version":3
}
"file_extension":".py"
"mimetype":"text/x-python"
"name":"python"
"nbconvert_exporter":"python"
"pygments_lexer":"ipython3"
"version":"3.12.7"
}
}
"nbformat":4
"nbformat_minor":5
}
